---
# https://github.com/suzuki-shunsuke/github-comment
exec:
  compare-circleci-config:
    - when: ExitCode != 0
      template: |
        :x: {{template "link" .}}

        .circleci/config.yml doesn't match with the result of `circleci-config-merge`.

        Don't edit .circleci/config.yml directly!
        .circleci/config.yml is being split per service.
        If you want to update .circleci/config.yml, update split files and run

        ```
        $ make circleci
        ```

        and commit both split files and .circleci/config.yml.
